"""The installed package must carry the things it serves.

`api/app.py` mounts `/ui` from `<package>/web`, and the offline help lives under
`<package>/web/docs`. Setuptools ships only `.py` files unless `package-data`
says otherwise, so a missing declaration produces an install whose console is a
404 and whose help is absent -- with nothing failing at build time to say so.

These tests are cheap and exist because that failure is invisible until someone
installs the wheel on a machine that is not the build machine.
"""

from __future__ import annotations

import fnmatch
import pathlib
import tomllib

PYPROJECT = pathlib.Path("pyproject.toml")
PACKAGE_ROOT = pathlib.Path("src/chaos")


def _package_data_patterns() -> list[str]:
    config = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    return config["tool"]["setuptools"]["package-data"]["chaos"]


def _web_assets() -> list[pathlib.Path]:
    return [
        path
        for path in PACKAGE_ROOT.rglob("*")
        if path.is_file() and path.suffix != ".py" and "web" in path.parts
    ]


def test_every_web_asset_is_declared_as_package_data():
    patterns = _package_data_patterns()
    uncovered = []
    for path in _web_assets():
        relative = path.relative_to(PACKAGE_ROOT).as_posix()
        if not any(fnmatch.fnmatch(relative, pattern) for pattern in patterns):
            uncovered.append(relative)

    assert not uncovered, (
        "These files are served at runtime but would not ship in the wheel. "
        "Add a pattern to [tool.setuptools.package-data] in pyproject.toml: "
        f"{sorted(uncovered)[:10]}"
    )


def test_the_console_entry_points_are_covered():
    """The specific files whose absence turns the console into a 404."""
    patterns = _package_data_patterns()
    for required in ("web/index.html", "web/annunciator.html", "web/app.js", "web/styles.css"):
        assert (PACKAGE_ROOT / required).is_file(), f"{required} is missing from the source tree"
        assert any(fnmatch.fnmatch(required, pattern) for pattern in patterns), (
            f"{required} is not covered by package-data"
        )


def test_the_offline_help_is_covered():
    """The help is what someone opens when the platform is down."""
    patterns = _package_data_patterns()
    single_file = "web/docs/chaos-help-offline.html"
    assert (PACKAGE_ROOT / single_file).is_file(), (
        "The offline help build is missing. It is generated by tools/build_docs.py "
        "and committed, so that an install carries it without a build step."
    )
    assert any(fnmatch.fnmatch(single_file, pattern) for pattern in patterns)
