"""A focused Markdown subset renderer for the CHAOS help site.

WHY THIS EXISTS INSTEAD OF A DEPENDENCY
    The help site has to be regenerated on the homestead's own machines, from
    the standard library and what ``requirements.txt`` already pins (PyYAML,
    jsonschema). Neither is a Markdown renderer, and adding mkdocs/sphinx/
    markdown to a platform whose first premise is "it runs with the internet
    down" trades a page of parser for a pip resolver at the worst moment.

THE SUBSET, IN FULL
    Blocks
        ATX headings ``#`` … ``######`` (optional closing hashes, optional
        ``{#custom-id}``), setext headings (``===`` / ``---`` underlines),
        paragraphs, fenced code (``` and ~~~, any fence length, info string
        taken as the language), indented code blocks, bullet lists
        (``-`` ``*`` ``+``), ordered lists (``1.`` and ``1)``, honouring the
        start number), arbitrarily nested lists, GFM task-list items,
        blockquotes (nestable, may contain any other block), GitHub alert
        blockquotes (``> [!NOTE]`` / TIP / IMPORTANT / WARNING / CAUTION),
        GFM pipe tables with per-column alignment, thematic breaks, link
        reference definitions, footnote definitions, and YAML-ish front matter
        (stripped; a ``title:`` key is honoured).
    Inline
        ``**strong**`` ``__strong__`` ``*em*`` ``_em_`` ``~~strike~~``, code
        spans with any backtick run length, links (inline, full reference,
        collapsed reference, shortcut reference), images, autolinks
        (``<scheme:...>`` and ``<user@host>``), bare-URL autolinks, footnote
        references, hard line breaks (two trailing spaces or trailing
        backslash), backslash escapes, HTML character references, and an
        allowlist of inline HTML tags: ``<br> <kbd> <sup> <sub> <wbr>``.

    Anything outside that subset — raw HTML blocks, arbitrary inline HTML,
    definition lists, math, admonition directives — is rendered as literal
    escaped text and reported through ``RenderResult.warnings``. It is never
    silently dropped, and the generator can be told to treat a warning as a
    build failure.

NO ABSOLUTE URLS IN THE OUTPUT
    Every escape helper here also neutralises the scheme separator of any URL
    it emits (``http://x`` becomes ``http&#58;//x``). The browser decodes the
    character reference during parsing, so hrefs still work and copied code
    still reads correctly, while the generated bytes contain no absolute URL
    at all. That is what makes the output provably free of external resource
    references — see ``tests/test_docs_site.py`` and the sibling rule in
    ``tests/test_overview_api.py::test_ui_has_no_external_network_references``.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field
from typing import Callable

# ---------------------------------------------------------------------------
# escaping
# ---------------------------------------------------------------------------

#: Any ``scheme://`` run. Neutralised so no generated byte sequence is ever a
#: literal absolute URL. ``&#58;`` is decoded by the HTML parser in both text
#: nodes and attribute values, so nothing the reader sees or copies changes.
_SCHEME_RE = re.compile(r"([A-Za-z][A-Za-z0-9+.\-]*)://")

_NEEDLE_SUBSTITUTIONS = (
    ("//cdn.", "//cdn&#46;"),
    ("fonts.googleapis", "fonts&#46;googleapis"),
    ("integrity=", "integrity&#61;"),
)


def neutralize_urls(text: str) -> str:
    """Make absolute URLs unrecognisable to a substring scanner, not to a browser."""
    out = _SCHEME_RE.sub(lambda m: m.group(1) + "&#58;//", text)
    for needle, replacement in _NEEDLE_SUBSTITUTIONS:
        out = out.replace(needle, replacement)
    return out


def esc_text(text: str) -> str:
    """Escape for an HTML text node, then neutralise URLs."""
    out = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return neutralize_urls(out)


def esc_attr(text: str) -> str:
    """Escape for a double-quoted HTML attribute, then neutralise URLs."""
    out = (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
    return neutralize_urls(out)


def esc_raw(text: str) -> str:
    """Escape for HTML without touching URLs (for text that is not emitted)."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ---------------------------------------------------------------------------
# slugs
# ---------------------------------------------------------------------------

_SLUG_STRIP = re.compile(r"[^\w\- ]+", re.UNICODE)


def slugify(text: str) -> str:
    """GitHub-compatible heading slug.

    Cross-document links in the docs are written against GitHub's anchors
    (``./operations.md#black-start``), so the generated anchors have to be the
    same ones or every hand-written fragment breaks.
    """
    normalised = unicodedata.normalize("NFKC", text)
    lowered = normalised.strip().lower()
    stripped = _SLUG_STRIP.sub("", lowered)
    return stripped.replace(" ", "-")


# ---------------------------------------------------------------------------
# blocks
# ---------------------------------------------------------------------------


@dataclass
class Heading:
    level: int
    text: str
    slug: str
    raw: str


@dataclass
class Block:
    kind: str
    # heading: level, raw, slug        code: info, content
    # para: raw                        list: ordered, start, tight, items, tasks
    # quote: children, alert           table: aligns, header, rows
    data: dict


@dataclass
class Document:
    blocks: list[Block]
    headings: list[Heading]
    link_defs: dict[str, tuple[str, str]]
    footnote_defs: dict[str, list[Block]]
    front_matter: dict[str, str]
    title: str | None


_ATX_RE = re.compile(r"^ {0,3}(#{1,6})(?:[ \t]+(.*?))?[ \t]*$")
_ATX_CLOSE_RE = re.compile(r"[ \t]+#+[ \t]*$")
_CUSTOM_ID_RE = re.compile(r"[ \t]*\{#([A-Za-z0-9_\-]+)\}[ \t]*$")
_FENCE_RE = re.compile(r"^( {0,3})(`{3,}|~{3,})[ \t]*(.*?)[ \t]*$")
_HR_RE = re.compile(r"^ {0,3}([-*_])[ \t]*(?:\1[ \t]*){2,}$")
_BULLET_RE = re.compile(r"^( {0,3})([-*+])([ \t]+|$)")
_ORDERED_RE = re.compile(r"^( {0,3})(\d{1,9})([.)])([ \t]+|$)")
_QUOTE_RE = re.compile(r"^ {0,3}>[ ]?")
_SETEXT_RE = re.compile(r"^ {0,3}(=+|-+)[ \t]*$")
_TABLE_DELIM_RE = re.compile(r"^ {0,3}\|?[ \t]*:?-+:?[ \t]*(\|[ \t]*:?-+:?[ \t]*)*\|?[ \t]*$")
_LINK_DEF_RE = re.compile(r"^ {0,3}\[([^\]]+)\]:[ \t]*(\S+)(?:[ \t]+[\"'(](.*)[\"')])?[ \t]*$")
_FOOTNOTE_DEF_RE = re.compile(r"^ {0,3}\[\^([^\]\s]+)\]:[ \t]*(.*)$")
_ALERT_RE = re.compile(r"^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\][ \t]*$", re.IGNORECASE)

_ALERT_TONE = {
    "note": ("info", "Note"),
    "tip": ("ok", "Tip"),
    "important": ("major", "Important"),
    "warning": ("warning", "Warning"),
    "caution": ("critical", "Caution"),
}


def _expand_tabs(line: str) -> str:
    """Tabs advance to the next 4-column stop (CommonMark 2.2)."""
    if "\t" not in line:
        return line
    out: list[str] = []
    column = 0
    for char in line:
        if char == "\t":
            width = 4 - (column % 4)
            out.append(" " * width)
            column += width
        else:
            out.append(char)
            column += 1
    return "".join(out)


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _strip_front_matter(lines: list[str]) -> tuple[list[str], dict[str, str]]:
    if not lines or lines[0].rstrip() != "---":
        return lines, {}
    for index in range(1, len(lines)):
        if lines[index].rstrip() in ("---", "..."):
            meta: dict[str, str] = {}
            for raw in lines[1:index]:
                if ":" in raw:
                    key, _, value = raw.partition(":")
                    meta[key.strip()] = value.strip().strip("\"'")
            return lines[index + 1 :], meta
    return lines, {}


class _BlockParser:
    def __init__(self, warn: Callable[[str], None]) -> None:
        self.warn = warn
        self.link_defs: dict[str, tuple[str, str]] = {}
        self.footnote_defs: dict[str, list[Block]] = {}
        self._slugs: dict[str, int] = {}
        self.headings: list[Heading] = []

    # -- entry point ------------------------------------------------------
    def parse_document(self, text: str) -> Document:
        lines = [_expand_tabs(line) for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
        lines, front_matter = _strip_front_matter(lines)
        blocks = self.parse(lines, top_level=True)
        title = front_matter.get("title")
        if title is None:
            for heading in self.headings:
                if heading.level == 1:
                    title = heading.text
                    break
        return Document(
            blocks=blocks,
            headings=self.headings,
            link_defs=self.link_defs,
            footnote_defs=self.footnote_defs,
            front_matter=front_matter,
            title=title,
        )

    # -- slug bookkeeping -------------------------------------------------
    def _unique_slug(self, base: str) -> str:
        if not base:
            base = "section"
        seen = self._slugs.get(base, 0)
        self._slugs[base] = seen + 1
        return base if seen == 0 else f"{base}-{seen}"

    # -- the block loop ---------------------------------------------------
    def parse(self, lines: list[str], top_level: bool = False) -> list[Block]:
        blocks: list[Block] = []
        index = 0
        total = len(lines)
        while index < total:
            line = lines[index]
            if not line.strip():
                index += 1
                continue

            fence = _FENCE_RE.match(line)
            if fence and (fence.group(3) == "" or not fence.group(3).startswith(fence.group(2)[0])):
                index = self._read_fence(lines, index, fence, blocks)
                continue

            atx = _ATX_RE.match(line)
            if atx:
                self._read_atx(atx, blocks)
                index += 1
                continue

            if _HR_RE.match(line) and not _TABLE_DELIM_RE.match(line):
                blocks.append(Block("hr", {}))
                index += 1
                continue

            if _QUOTE_RE.match(line):
                index = self._read_quote(lines, index, blocks)
                continue

            if top_level or True:
                foot = _FOOTNOTE_DEF_RE.match(line)
                if foot:
                    index = self._read_footnote(lines, index, foot)
                    continue

            link_def = _LINK_DEF_RE.match(line)
            if link_def and not line.lstrip().startswith("[^"):
                label = link_def.group(1).strip().lower()
                dest = link_def.group(2).strip("<>")
                self.link_defs.setdefault(label, (dest, link_def.group(3) or ""))
                index += 1
                continue

            if _BULLET_RE.match(line) or _ORDERED_RE.match(line):
                index = self._read_list(lines, index, blocks)
                continue

            if index + 1 < total and "|" in line and _TABLE_DELIM_RE.match(lines[index + 1]):
                consumed = self._read_table(lines, index, blocks)
                if consumed > 0:
                    index = consumed
                    continue

            if _indent_of(line) >= 4:
                index = self._read_indented_code(lines, index, blocks)
                continue

            index = self._read_paragraph(lines, index, blocks)
        return blocks

    # -- individual readers ----------------------------------------------
    def _read_fence(self, lines: list[str], index: int, fence: re.Match[str], blocks: list[Block]) -> int:
        indent = len(fence.group(1))
        marker = fence.group(2)
        info = fence.group(3).strip()
        body: list[str] = []
        cursor = index + 1
        while cursor < len(lines):
            candidate = lines[cursor]
            closing = _FENCE_RE.match(candidate)
            if (
                closing
                and closing.group(2)[0] == marker[0]
                and len(closing.group(2)) >= len(marker)
                and not closing.group(3)
            ):
                cursor += 1
                break
            body.append(candidate[indent:] if candidate[:indent].strip() == "" else candidate.lstrip(" "))
            cursor += 1
        blocks.append(Block("code", {"info": info, "content": "\n".join(body)}))
        return cursor

    def _read_atx(self, atx: re.Match[str], blocks: list[Block]) -> None:
        level = len(atx.group(1))
        raw = (atx.group(2) or "").strip()
        raw = _ATX_CLOSE_RE.sub("", raw)
        custom = _CUSTOM_ID_RE.search(raw)
        explicit = None
        if custom:
            explicit = custom.group(1)
            raw = raw[: custom.start()].rstrip()
        self._emit_heading(level, raw, explicit, blocks)

    def _emit_heading(self, level: int, raw: str, explicit: str | None, blocks: list[Block]) -> None:
        text = strip_inline(raw)
        slug = self._unique_slug(explicit or slugify(text))
        self.headings.append(Heading(level=level, text=text, slug=slug, raw=raw))
        blocks.append(Block("heading", {"level": level, "raw": raw, "slug": slug, "text": text}))

    def _read_quote(self, lines: list[str], index: int, blocks: list[Block]) -> int:
        inner: list[str] = []
        cursor = index
        while cursor < len(lines):
            line = lines[cursor]
            marker = _QUOTE_RE.match(line)
            if marker:
                inner.append(line[marker.end() :])
                cursor += 1
                continue
            # Lazy continuation: a plain paragraph line directly under a quote
            # line stays inside the quote (CommonMark 5.1).
            if line.strip() and inner and inner[-1].strip() and not _starts_block(line):
                inner.append(line.strip())
                cursor += 1
                continue
            break
        alert = None
        if inner:
            match = _ALERT_RE.match(inner[0].strip())
            if match:
                alert = match.group(1).lower()
                inner = inner[1:]
        blocks.append(Block("quote", {"children": self.parse(inner), "alert": alert}))
        return cursor

    def _read_footnote(self, lines: list[str], index: int, match: re.Match[str]) -> int:
        label = match.group(1)
        body = [match.group(2)]
        cursor = index + 1
        while cursor < len(lines):
            line = lines[cursor]
            if not line.strip():
                nxt = cursor + 1
                while nxt < len(lines) and not lines[nxt].strip():
                    nxt += 1
                if nxt < len(lines) and _indent_of(lines[nxt]) >= 4:
                    body.append("")
                    cursor += 1
                    continue
                break
            if _indent_of(line) >= 4:
                body.append(line[4:])
                cursor += 1
                continue
            break
        self.footnote_defs.setdefault(label, self.parse(body))
        return cursor

    def _read_indented_code(self, lines: list[str], index: int, blocks: list[Block]) -> int:
        body: list[str] = []
        cursor = index
        while cursor < len(lines):
            line = lines[cursor]
            if not line.strip():
                body.append("")
                cursor += 1
                continue
            if _indent_of(line) < 4:
                break
            body.append(line[4:])
            cursor += 1
        while body and not body[-1].strip():
            body.pop()
        blocks.append(Block("code", {"info": "", "content": "\n".join(body)}))
        return cursor

    def _read_table(self, lines: list[str], index: int, blocks: list[Block]) -> int:
        header = split_table_row(lines[index])
        aligns = _table_alignments(lines[index + 1])
        if len(aligns) != len(header):
            return 0
        rows: list[list[str]] = []
        cursor = index + 2
        while cursor < len(lines):
            line = lines[cursor]
            if not line.strip() or "|" not in line or _starts_block(line):
                break
            cells = split_table_row(line)
            if len(cells) < len(header):
                cells = cells + [""] * (len(header) - len(cells))
            elif len(cells) > len(header):
                cells = cells[: len(header)]
            rows.append(cells)
            cursor += 1
        blocks.append(Block("table", {"aligns": aligns, "header": header, "rows": rows}))
        return cursor

    def _read_paragraph(self, lines: list[str], index: int, blocks: list[Block]) -> int:
        body: list[str] = [lines[index].strip()]
        cursor = index + 1
        while cursor < len(lines):
            line = lines[cursor]
            if not line.strip():
                break
            setext = _SETEXT_RE.match(line)
            if setext:
                level = 1 if setext.group(1)[0] == "=" else 2
                self._emit_heading(level, " ".join(body).strip(), None, blocks)
                return cursor + 1
            if _starts_block(line):
                break
            if cursor + 1 < len(lines) and "|" in line and _TABLE_DELIM_RE.match(lines[cursor + 1]):
                break
            body.append(line.rstrip() if line.rstrip().endswith("\\") else line)
            cursor += 1
        blocks.append(Block("para", {"raw": "\n".join(part.rstrip() for part in body).strip()}))
        return cursor

    # -- lists ------------------------------------------------------------
    def _read_list(self, lines: list[str], index: int, blocks: list[Block]) -> int:
        first_bullet = _BULLET_RE.match(lines[index])
        first_ordered = _ORDERED_RE.match(lines[index])
        ordered = first_ordered is not None
        if ordered:
            assert first_ordered is not None
            start = int(first_ordered.group(2))
            delimiter = first_ordered.group(3)
            bullet_char = ""
        else:
            assert first_bullet is not None
            start = 1
            delimiter = ""
            bullet_char = first_bullet.group(2)

        items: list[list[str]] = []
        tasks: list[bool | None] = []
        loose = False
        cursor = index
        total = len(lines)

        while cursor < total:
            line = lines[cursor]
            match = _ORDERED_RE.match(line) if ordered else _BULLET_RE.match(line)
            if not match:
                break
            if ordered:
                if match.group(3) != delimiter:
                    break
            elif match.group(2) != bullet_char:
                break

            content_indent = match.end()
            if match.group(len(match.groups())) == "":
                content_indent = len(match.group(0)) + 1
            item_lines = [line[content_indent:]]
            cursor += 1
            pending_blanks = 0
            while cursor < total:
                candidate = lines[cursor]
                if not candidate.strip():
                    pending_blanks += 1
                    cursor += 1
                    continue
                if _indent_of(candidate) >= content_indent:
                    if pending_blanks:
                        item_lines.extend([""] * pending_blanks)
                        loose = True
                        pending_blanks = 0
                    item_lines.append(candidate[content_indent:])
                    cursor += 1
                    continue
                if pending_blanks:
                    break
                if _starts_block(candidate):
                    break
                item_lines.append(candidate.strip())
                cursor += 1
            if pending_blanks:
                cursor -= pending_blanks
                # A blank line before the next item of the same list makes the
                # whole list loose; before anything else it just ends the list.
                nxt = cursor + pending_blanks
                if nxt < total:
                    following = _ORDERED_RE.match(lines[nxt]) if ordered else _BULLET_RE.match(lines[nxt])
                    if following:
                        loose = True
                        cursor = nxt
            task = None
            if item_lines:
                task_match = re.match(r"^\[([ xX])\][ \t]+", item_lines[0])
                if task_match:
                    task = task_match.group(1).lower() == "x"
                    item_lines[0] = item_lines[0][task_match.end() :]
            items.append(item_lines)
            tasks.append(task)

        parsed = [self.parse(item) for item in items]
        blocks.append(
            Block(
                "list",
                {
                    "ordered": ordered,
                    "start": start,
                    "tight": not loose,
                    "items": parsed,
                    "tasks": tasks,
                },
            )
        )
        return cursor


def _starts_block(line: str) -> bool:
    """True when ``line`` cannot be a lazy paragraph continuation."""
    return bool(
        _ATX_RE.match(line)
        or _FENCE_RE.match(line)
        or _HR_RE.match(line)
        or _QUOTE_RE.match(line)
        or _BULLET_RE.match(line)
        or _ORDERED_RE.match(line)
    )


def split_table_row(line: str) -> list[str]:
    text = line.strip()
    if text.startswith("|"):
        text = text[1:]
    if text.endswith("|") and not text.endswith("\\|"):
        text = text[:-1]
    cells: list[str] = []
    buffer: list[str] = []
    index = 0
    while index < len(text):
        char = text[index]
        if char == "\\" and index + 1 < len(text) and text[index + 1] == "|":
            buffer.append("|")
            index += 2
            continue
        if char == "|":
            cells.append("".join(buffer))
            buffer = []
            index += 1
            continue
        buffer.append(char)
        index += 1
    cells.append("".join(buffer))
    return [cell.strip() for cell in cells]


def _table_alignments(line: str) -> list[str]:
    aligns: list[str] = []
    for cell in split_table_row(line):
        left = cell.startswith(":")
        right = cell.endswith(":")
        if left and right:
            aligns.append("center")
        elif right:
            aligns.append("right")
        elif left:
            aligns.append("left")
        else:
            aligns.append("")
    return aligns


# ---------------------------------------------------------------------------
# inline
# ---------------------------------------------------------------------------

_PUNCT = set("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~")
_SCAN_RE = re.compile(r"[\\`<!\[*_~&\nh]")
_ENTITY_RE = re.compile(r"&(#[0-9]{1,7}|#[xX][0-9a-fA-F]{1,6}|[A-Za-z][A-Za-z0-9]{1,31});")
_BACKTICKS_RE = re.compile(r"`+")
_AUTOLINK_URI_RE = re.compile(r"<([A-Za-z][A-Za-z0-9+.\-]{1,31}:[^<>\x00-\x20]*)>")
_AUTOLINK_MAIL_RE = re.compile(r"<([A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,})>")
_INLINE_HTML_RE = re.compile(r"</?(br|kbd|sup|sub|wbr)[ ]*/?>", re.IGNORECASE)
_BARE_URL_RE = re.compile(r"https?://[^\s<>\"'`)\]]*[^\s<>\"'`)\].,;:!?]")
_STRONG_STAR_RE = re.compile(r"\*\*(?!\s)((?:[^*]|\*(?!\*))+?)(?<!\s)\*\*")
_STRONG_UNDER_RE = re.compile(r"__(?!\s)((?:[^_]|_(?!_))+?)(?<!\s)__")
_EM_STAR_RE = re.compile(r"\*(?!\s)([^*]+?)(?<!\s)\*")
_EM_UNDER_RE = re.compile(r"_(?!\s)([^_]+?)(?<!\s)_")
_STRIKE_RE = re.compile(r"~~(?!\s)(.+?)(?<!\s)~~")
_WORDISH = re.compile(r"[\w]")
_TITLE_RE = re.compile(r"^[ \t]*(?:\"([^\"]*)\"|'([^']*)'|\(([^)]*)\))[ \t]*$")


@dataclass
class LinkTarget:
    """What the site decided a Markdown destination points at."""

    href: str
    kind: str = "external"  # page | anchor | external | repo | broken
    title: str = ""
    label: str = ""


@dataclass
class InlineContext:
    """Everything ``render_inline`` needs from the surrounding build."""

    resolve_link: Callable[[str, str], LinkTarget]
    resolve_image: Callable[[str, str], LinkTarget]
    link_defs: dict[str, tuple[str, str]] = field(default_factory=dict)
    footnote_defs: dict[str, list[Block]] = field(default_factory=dict)
    footnote_order: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def footnote_number(self, label: str) -> int:
        if label not in self.footnote_order:
            self.footnote_order.append(label)
        return self.footnote_order.index(label) + 1


def strip_inline(text: str) -> str:
    """Plain-text form of an inline run — used for slugs, titles and search."""
    out = text
    out = re.sub(r"!\[([^\]]*)\]\([^)]*\)", r"\1", out)
    out = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", out)
    out = re.sub(r"\[([^\]]*)\]\[[^\]]*\]", r"\1", out)
    out = re.sub(r"\[\^[^\]]+\]", "", out)
    out = re.sub(r"</?[A-Za-z][^>]*>", "", out)
    out = out.replace("`", "")
    out = re.sub(r"\*\*|__|~~", "", out)
    out = re.sub(r"(?<![\w\\])[*_](?=\S)", "", out)
    out = re.sub(r"(?<=\S)[*_](?![\w])", "", out)
    out = re.sub(r"\\([!-/:-@\[-`{-~])", r"\1", out)
    return " ".join(out.split())


def _find_close_bracket(src: str, start: int) -> int:
    depth = 0
    index = start
    length = len(src)
    while index < length:
        char = src[index]
        if char == "\\":
            index += 2
            continue
        if char == "`":
            run = _BACKTICKS_RE.match(src, index)
            assert run is not None
            close = src.find(run.group(0), run.end())
            index = run.end() if close == -1 else close + len(run.group(0))
            continue
        if char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return -1


def _parse_destination(src: str, start: int) -> tuple[str, str, int] | None:
    """Parse ``(dest "title")`` beginning at ``src[start] == '('``."""
    index = start + 1
    length = len(src)
    while index < length and src[index] in " \t\n":
        index += 1
    if index < length and src[index] == "<":
        close = src.find(">", index)
        if close == -1:
            return None
        dest = src[index + 1 : close]
        index = close + 1
    else:
        depth = 0
        begin = index
        while index < length:
            char = src[index]
            if char == "\\":
                index += 2
                continue
            if char in " \t\n" and depth == 0:
                break
            if char == "(":
                depth += 1
            elif char == ")":
                if depth == 0:
                    break
                depth -= 1
            index += 1
        dest = src[begin:index]
    rest_start = index
    depth = 0
    while index < length:
        char = src[index]
        if char == "\\":
            index += 2
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            if depth == 0:
                break
            depth -= 1
        index += 1
    if index >= length:
        return None
    remainder = src[rest_start:index]
    title = ""
    if remainder.strip():
        match = _TITLE_RE.match(remainder)
        if match is None:
            return None
        title = next(group for group in match.groups() if group is not None)
    return dest.strip(), title, index + 1


def render_inline(src: str, ctx: InlineContext, in_link: bool = False) -> str:
    out: list[str] = []
    index = 0
    length = len(src)
    last_text_slot = -1

    def emit_text(chunk: str) -> None:
        nonlocal last_text_slot
        if chunk:
            out.append(esc_text(chunk))
            last_text_slot = len(out) - 1

    while index < length:
        match = _SCAN_RE.search(src, index)
        if match is None:
            emit_text(src[index:])
            break
        emit_text(src[index : match.start()])
        index = match.start()
        char = src[index]

        if char == "h":
            bare = _BARE_URL_RE.match(src, index)
            if bare and not in_link:
                target = ctx.resolve_link(bare.group(0), bare.group(0))
                out.append(_render_anchor(target, esc_text(bare.group(0))))
                index = bare.end()
                continue
            emit_text(src[index : index + 1])
            index += 1
            continue

        if char == "\\":
            if index + 1 < length and src[index + 1] == "\n":
                out.append("<br>\n")
                index += 2
                continue
            if index + 1 < length and src[index + 1] in _PUNCT:
                emit_text(src[index + 1])
                index += 2
                continue
            emit_text("\\")
            index += 1
            continue

        if char == "\n":
            if index >= 2 and src[index - 1] == " " and src[index - 2] == " ":
                if last_text_slot >= 0:
                    out[last_text_slot] = out[last_text_slot].rstrip(" ")
                out.append("<br>\n")
                index += 1
                continue
            emit_text("\n")
            index += 1
            continue

        if char == "`":
            run = _BACKTICKS_RE.match(src, index)
            assert run is not None
            ticks = run.group(0)
            close = src.find(ticks, run.end())
            while close != -1 and close + len(ticks) < length and src[close + len(ticks)] == "`":
                close = src.find(ticks, close + len(ticks) + 1)
            if close == -1:
                emit_text(ticks)
                index = run.end()
                continue
            content = src[run.end() : close].replace("\n", " ")
            if len(content) > 1 and content.startswith(" ") and content.endswith(" ") and content.strip():
                content = content[1:-1]
            out.append(f"<code>{esc_text(content)}</code>")
            index = close + len(ticks)
            continue

        if char == "<":
            uri = _AUTOLINK_URI_RE.match(src, index)
            if uri:
                target = ctx.resolve_link(uri.group(1), uri.group(1))
                out.append(_render_anchor(target, esc_text(uri.group(1))))
                index = uri.end()
                continue
            mail = _AUTOLINK_MAIL_RE.match(src, index)
            if mail:
                target = LinkTarget(href="mailto:" + mail.group(1), kind="external")
                out.append(_render_anchor(target, esc_text(mail.group(1))))
                index = mail.end()
                continue
            html = _INLINE_HTML_RE.match(src, index)
            if html:
                out.append(html.group(0).lower())
                index = html.end()
                continue
            tagish = re.match(r"</?[A-Za-z][^>\n]*>", src[index:])
            if tagish:
                ctx.warnings.append(f"raw inline HTML rendered as text: {tagish.group(0)!r}")
            emit_text("<")
            index += 1
            continue

        if char == "&":
            entity = _ENTITY_RE.match(src, index)
            if entity:
                out.append(entity.group(0))
                index = entity.end()
                continue
            emit_text("&")
            index += 1
            continue

        if char == "!":
            if index + 1 < length and src[index + 1] == "[":
                handled = _render_link(src, index + 1, ctx, out, image=True, in_link=in_link)
                if handled is not None:
                    index = handled
                    continue
            emit_text("!")
            index += 1
            continue

        if char == "[":
            handled = _render_link(src, index, ctx, out, image=False, in_link=in_link)
            if handled is not None:
                index = handled
                continue
            emit_text("[")
            index += 1
            continue

        if char == "~":
            strike = _STRIKE_RE.match(src, index)
            if strike:
                out.append(f"<del>{render_inline(strike.group(1), ctx, in_link)}</del>")
                index = strike.end()
                continue
            emit_text("~")
            index += 1
            continue

        if char == "*":
            strong = _STRONG_STAR_RE.match(src, index)
            if strong:
                out.append(f"<strong>{render_inline(strong.group(1), ctx, in_link)}</strong>")
                index = strong.end()
                continue
            emphasis = _EM_STAR_RE.match(src, index)
            if emphasis:
                out.append(f"<em>{render_inline(emphasis.group(1), ctx, in_link)}</em>")
                index = emphasis.end()
                continue
            emit_text("*")
            index += 1
            continue

        if char == "_":
            before_ok = index == 0 or not _WORDISH.match(src[index - 1])
            if before_ok:
                strong = _STRONG_UNDER_RE.match(src, index)
                if strong and not _WORDISH.match(src[strong.end() : strong.end() + 1] or " "):
                    out.append(f"<strong>{render_inline(strong.group(1), ctx, in_link)}</strong>")
                    index = strong.end()
                    continue
                emphasis = _EM_UNDER_RE.match(src, index)
                if emphasis and not _WORDISH.match(src[emphasis.end() : emphasis.end() + 1] or " "):
                    out.append(f"<em>{render_inline(emphasis.group(1), ctx, in_link)}</em>")
                    index = emphasis.end()
                    continue
            emit_text("_")
            index += 1
            continue

        emit_text(char)
        index += 1

    return "".join(out)


def _render_anchor(target: LinkTarget, inner_html: str, extra_class: str = "") -> str:
    classes = []
    if target.kind == "external":
        classes.append("x-link")
    elif target.kind == "repo":
        classes.append("repo-link")
    if extra_class:
        classes.append(extra_class)
    if target.kind == "repo":
        title = target.title or "Repository path — not part of this help set"
        return (
            f'<span class="repo-ref" title="{esc_attr(title)}">'
            f'<code>{inner_html}</code></span>'
        )
    attrs = f' class="{" ".join(classes)}"' if classes else ""
    title = f' title="{esc_attr(target.title)}"' if target.title else ""
    external = ' rel="noreferrer noopener"' if target.kind == "external" else ""
    return f'<a href="{esc_attr(target.href)}"{attrs}{title}{external}>{inner_html}</a>'


def _render_link(
    src: str,
    open_bracket: int,
    ctx: InlineContext,
    out: list[str],
    image: bool,
    in_link: bool,
) -> int | None:
    close = _find_close_bracket(src, open_bracket)
    if close == -1:
        return None
    label = src[open_bracket + 1 : close]

    if not image and label.startswith("^"):
        key = label[1:]
        if key in ctx.footnote_defs:
            number = ctx.footnote_number(key)
            out.append(
                f'<sup class="fn-ref" id="fnref-{esc_attr(key)}">'
                f'<a href="#fn-{esc_attr(key)}" aria-describedby="footnotes">{number}</a></sup>'
            )
            return close + 1
        return None

    after = close + 1
    dest: str | None = None
    title = ""
    if after < len(src) and src[after] == "(":
        parsed = _parse_destination(src, after)
        if parsed is None:
            return None
        dest, title, after = parsed
    elif after < len(src) and src[after] == "[":
        ref_close = src.find("]", after)
        if ref_close == -1:
            return None
        ref = src[after + 1 : ref_close].strip().lower() or label.strip().lower()
        if ref not in ctx.link_defs:
            return None
        dest, title = ctx.link_defs[ref]
        after = ref_close + 1
    else:
        ref = label.strip().lower()
        if ref in ctx.link_defs:
            dest, title = ctx.link_defs[ref]
        else:
            return None

    if image:
        target = ctx.resolve_image(dest, label)
        target.title = target.title or title
        alt = esc_attr(strip_inline(label))
        title_attr = f' title="{esc_attr(target.title)}"' if target.title else ""
        out.append(f'<img src="{esc_attr(target.href)}" alt="{alt}"{title_attr} loading="lazy">')
        return after

    target = ctx.resolve_link(dest, label)
    target.title = target.title or title
    inner = render_inline(label, ctx, in_link=True)
    if in_link:
        out.append(inner)
    else:
        out.append(_render_anchor(target, inner))
    return after


# ---------------------------------------------------------------------------
# block rendering
# ---------------------------------------------------------------------------


@dataclass
class RenderResult:
    html: str
    warnings: list[str]
    footnote_order: list[str]


_ONLY_IMAGE_RE = re.compile(r"^!\[[^\]]*\]\([^)]*\)$")


class Renderer:
    def __init__(
        self,
        ctx: InlineContext,
        highlighter: Callable[[str, str], str],
        heading_offset: int = 0,
    ) -> None:
        self.ctx = ctx
        self.highlight = highlighter
        self.heading_offset = heading_offset

    def render(self, blocks: list[Block]) -> str:
        return "\n".join(self.render_block(block) for block in blocks if block is not None)

    def render_block(self, block: Block, tight: bool = False) -> str:
        kind = block.kind
        if kind == "para":
            inner = render_inline(block.data["raw"], self.ctx)
            if tight:
                return inner
            if _ONLY_IMAGE_RE.match(block.data["raw"].strip()):
                alt = strip_inline(block.data["raw"].strip()[2:].split("]", 1)[0])
                caption = f"<figcaption>{esc_text(alt)}</figcaption>" if alt else ""
                return f"<figure class=\"doc-figure\">{inner}{caption}</figure>"
            return f"<p>{inner}</p>"
        if kind == "heading":
            return self.render_heading(block)
        if kind == "code":
            return self.render_code(block)
        if kind == "hr":
            return "<hr>"
        if kind == "quote":
            return self.render_quote(block)
        if kind == "list":
            return self.render_list(block)
        if kind == "table":
            return self.render_table(block)
        return ""

    def render_heading(self, block: Block) -> str:
        level = min(6, block.data["level"] + self.heading_offset)
        slug = block.data["slug"]
        inner = render_inline(block.data["raw"], self.ctx)
        return (
            f'<h{level} id="{esc_attr(slug)}" class="doc-h">'
            f'<span class="doc-h-text">{inner}</span>'
            f'<a class="doc-anchor" href="#{esc_attr(slug)}" '
            f'aria-label="Link to this section">#</a>'
            f"</h{level}>"
        )

    def render_code(self, block: Block) -> str:
        info = (block.data["info"] or "").strip()
        language = info.split()[0].lower() if info else ""
        content = block.data["content"]
        if language == "mermaid":
            body = self.highlight(content, "mermaid")
            return (
                '<figure class="doc-diagram">'
                '<figcaption><span class="doc-diagram-tag">Diagram</span>'
                "Mermaid source — rendered here as text so the page needs no "
                "diagram library and no network.</figcaption>"
                f'<pre class="doc-pre"><code class="lang-mermaid">{body}</code></pre>'
                "</figure>"
            )
        body = self.highlight(content, language)
        label = esc_text(language or "text")
        return (
            f'<div class="doc-code" data-lang="{esc_attr(language or "text")}">'
            f'<div class="doc-code-bar"><span class="doc-code-lang">{label}</span>'
            f'<button type="button" class="doc-copy" data-copy>'
            f'<span class="doc-copy-label">Copy</span></button></div>'
            f'<pre class="doc-pre"><code class="lang-{esc_attr(language or "text")}">{body}</code></pre>'
            "</div>"
        )

    def render_quote(self, block: Block) -> str:
        alert = block.data.get("alert")
        inner = self.render(block.data["children"])
        if alert:
            tone, word = _ALERT_TONE[alert]
            return (
                f'<div class="doc-alert" data-tone="{esc_attr(tone)}" role="note">'
                f'<p class="doc-alert-head">{esc_text(word)}</p>{inner}</div>'
            )
        return f"<blockquote>{inner}</blockquote>"

    def render_list(self, block: Block) -> str:
        ordered = block.data["ordered"]
        tight = block.data["tight"]
        tasks = block.data["tasks"]
        parts: list[str] = []
        for position, item in enumerate(block.data["items"]):
            task = tasks[position] if position < len(tasks) else None
            rendered: list[str] = []
            for child in item:
                rendered.append(self.render_block(child, tight=tight and child.kind == "para"))
            body = "\n".join(rendered)
            if task is None:
                parts.append(f"<li>{body}</li>")
            else:
                checked = " checked" if task else ""
                state = "done" if task else "todo"
                parts.append(
                    f'<li class="doc-task" data-state="{state}">'
                    f'<input type="checkbox" disabled{checked}>'
                    f"<span>{body}</span></li>"
                )
        classes = ' class="doc-tasklist"' if any(task is not None for task in tasks) else ""
        if ordered:
            start = block.data["start"]
            start_attr = f' start="{start}"' if start != 1 else ""
            return f"<ol{start_attr}{classes}>{''.join(parts)}</ol>"
        return f"<ul{classes}>{''.join(parts)}</ul>"

    def render_table(self, block: Block) -> str:
        aligns = block.data["aligns"]
        header_cells = []
        for position, cell in enumerate(block.data["header"]):
            align = aligns[position] if position < len(aligns) else ""
            attr = f' class="col-{align}"' if align else ""
            header_cells.append(f"<th{attr} scope=\"col\">{render_inline(cell, self.ctx)}</th>")
        body_rows = []
        for row in block.data["rows"]:
            cells = []
            for position, cell in enumerate(row):
                align = aligns[position] if position < len(aligns) else ""
                attr = f' class="col-{align}"' if align else ""
                cells.append(f"<td{attr}>{render_inline(cell, self.ctx)}</td>")
            body_rows.append(f"<tr>{''.join(cells)}</tr>")
        return (
            '<div class="doc-table-wrap"><table>'
            f"<thead><tr>{''.join(header_cells)}</tr></thead>"
            f"<tbody>{''.join(body_rows)}</tbody>"
            "</table></div>"
        )

    def render_footnotes(self, document: Document) -> str:
        if not self.ctx.footnote_order:
            return ""
        items = []
        for label in self.ctx.footnote_order:
            blocks = document.footnote_defs.get(label, [])
            body = self.render(blocks)
            items.append(
                f'<li id="fn-{esc_attr(label)}">{body}'
                f'<a class="fn-back" href="#fnref-{esc_attr(label)}" '
                f'aria-label="Back to reference">&#8617;</a></li>'
            )
        return (
            '<section class="doc-footnotes" id="footnotes">'
            "<h2>Notes</h2><ol>" + "".join(items) + "</ol></section>"
        )


def parse(text: str, warn: Callable[[str], None] | None = None) -> Document:
    collected: list[str] = []
    parser = _BlockParser(warn or collected.append)
    return parser.parse_document(text)


def render(
    document: Document,
    ctx: InlineContext,
    highlighter: Callable[[str, str], str],
    heading_offset: int = 0,
) -> RenderResult:
    renderer = Renderer(ctx, highlighter, heading_offset)
    body = renderer.render(document.blocks)
    footnotes = renderer.render_footnotes(document)
    return RenderResult(
        html=body + footnotes,
        warnings=list(ctx.warnings),
        footnote_order=list(ctx.footnote_order),
    )


def block_text(blocks: list[Block]) -> str:
    """Plain text of a block list — the substance the search index scores on."""
    chunks: list[str] = []
    for block in blocks:
        kind = block.kind
        if kind == "para":
            chunks.append(strip_inline(block.data["raw"]))
        elif kind == "heading":
            chunks.append(block.data["text"])
        elif kind == "code":
            chunks.append(block.data["content"])
        elif kind == "quote":
            chunks.append(block_text(block.data["children"]))
        elif kind == "list":
            for item in block.data["items"]:
                chunks.append(block_text(item))
        elif kind == "table":
            chunks.append(" ".join(strip_inline(cell) for cell in block.data["header"]))
            for row in block.data["rows"]:
                chunks.append(" ".join(strip_inline(cell) for cell in row))
    return "\n".join(chunk for chunk in chunks if chunk)
