"""The help site's client-side runtime.

Deliberate constraints, all of them about the outage case:

* **Classic script, not a module.** ``type="module"`` is fetched with CORS
  semantics, and Chrome blocks module fetches from ``file://``. A classic
  ``<script src>`` is not. The single-file build inlines this anyway, but the
  directory build has to open from a USB stick too.
* **No ``fetch``, no ``XMLHttpRequest``, no dynamic import.** The search index
  arrives as a global that the page already contains. Nothing is ever
  requested after load, so there is nothing to fail.
* **No absolute URLs, no external anything.** Every reference is same-document
  or a sibling file.
* **Everything is optional.** The content is real DOM before this file runs.
  If it throws, the reader still has the documentation.
"""

from __future__ import annotations

SITE_JS = r"""
/* Project CHAOS help site — generated by tools/build_docs.py.
   Editing this file edits a build artefact; change tools/docsite/runtime.py. */
(function () {
  "use strict";

  var CFG = window.__CHAOS_DOCS__ || { mode: "dir", pages: [], index: [] };
  var SINGLE = CFG.mode === "single";
  var PAGES = CFG.pages || [];
  var REC = CFG.index || [];
  var doc = document;

  function $(sel, scope) { return (scope || doc).querySelector(sel); }
  function $$(sel, scope) { return Array.prototype.slice.call((scope || doc).querySelectorAll(sel)); }
  function on(el, type, fn) { if (el) { el.addEventListener(type, fn); } }

  /* ------------------------------------------------------------------ theme */

  var THEME_KEY = "chaos-docs-theme";

  function readStored(key) {
    try { return window.localStorage.getItem(key); } catch (err) { return null; }
  }
  function writeStored(key, value) {
    try { window.localStorage.setItem(key, value); } catch (err) { /* private mode, file://, fine */ }
  }

  function applyTheme(mode) {
    if (mode === "light" || mode === "dark") {
      doc.documentElement.setAttribute("data-theme", mode);
    } else {
      doc.documentElement.removeAttribute("data-theme");
    }
    var btn = $("#theme-toggle");
    if (btn) {
      var label = mode === "light" ? "Light" : mode === "dark" ? "Dark" : "System";
      btn.setAttribute("aria-label", "Colour theme: " + label + ". Activate to change.");
      btn.setAttribute("title", "Colour theme: " + label);
      var text = $(".theme-label", btn);
      if (text) { text.textContent = label; }
    }
  }

  function cycleTheme() {
    var order = ["system", "dark", "light"];
    var current = readStored(THEME_KEY) || "system";
    var next = order[(order.indexOf(current) + 1) % order.length];
    writeStored(THEME_KEY, next);
    applyTheme(next);
  }

  applyTheme(readStored(THEME_KEY) || "system");
  on($("#theme-toggle"), "click", cycleTheme);

  /* ------------------------------------------------------------- navigation */

  on($("#nav-toggle"), "click", function () {
    var open = doc.body.getAttribute("data-nav") === "open";
    doc.body.setAttribute("data-nav", open ? "closed" : "open");
    this.setAttribute("aria-expanded", open ? "false" : "true");
  });

  function pageBySlug(slug) {
    for (var i = 0; i < PAGES.length; i++) { if (PAGES[i].s === slug) { return PAGES[i]; } }
    return null;
  }

  /* On a narrow screen the document list is a drawer over the page. Choosing
     something from it means you are done with it. */
  $$(".site-nav a").forEach(function (link) {
    on(link, "click", function () {
      if (doc.body.getAttribute("data-nav") === "open") {
        doc.body.setAttribute("data-nav", "closed");
        var toggle = $("#nav-toggle");
        if (toggle) { toggle.setAttribute("aria-expanded", "false"); }
      }
    });
  });

  function markNav(slug) {
    $$(".site-nav a").forEach(function (a) {
      if (a.getAttribute("data-page") === slug) { a.setAttribute("aria-current", "page"); }
      else { a.removeAttribute("aria-current"); }
    });
  }

  /* Single-file build: every document is an <article> in this one page, and
     the hash is "slug" or "slug__heading-anchor". */
  function showPage(slug, anchor, push) {
    var target = pageBySlug(slug) ? slug : (PAGES[0] ? PAGES[0].s : "");
    if (!target) { return; }
    $$(".doc-page").forEach(function (page) {
      var mine = page.getAttribute("data-page") === target;
      if (mine) { page.removeAttribute("hidden"); } else { page.setAttribute("hidden", "hidden"); }
    });
    $$(".toc-for").forEach(function (toc) {
      var mine = toc.getAttribute("data-page") === target;
      if (mine) { toc.removeAttribute("hidden"); } else { toc.setAttribute("hidden", "hidden"); }
    });
    markNav(target);
    var entry = pageBySlug(target);
    if (entry && CFG.title) { doc.title = entry.t + " — " + CFG.title; }
    if (push) {
      var hash = "#" + (anchor ? target + "__" + anchor : target);
      if (location.hash !== hash) { history.pushState(null, "", hash); }
    }
    /* Instant, never smooth. Switching document in the single-file build can
       mean animating across fourteen thousand pixels of a runbook, which reads
       as a stall and paints half-rasterised. Smooth scrolling stays where it
       belongs: plain in-page anchor clicks, handled natively by the browser. */
    var focus = anchor ? doc.getElementById(target + "__" + anchor) : null;
    if (focus) { focus.scrollIntoView({ behavior: "auto", block: "start" }); }
    else { window.scrollTo({ top: 0, left: 0, behavior: "auto" }); }
    var main = $("#content");
    if (main && typeof main.focus === "function") { main.focus({ preventScroll: true }); }
  }

  function routeFromHash() {
    var raw = (location.hash || "").replace(/^#/, "");
    if (!raw) { return { page: PAGES[0] ? PAGES[0].s : "", anchor: "" }; }
    var cut = raw.indexOf("__");
    if (cut >= 0) { return { page: raw.slice(0, cut), anchor: raw.slice(cut + 2) }; }
    return { page: raw, anchor: "" };
  }

  if (SINGLE) {
    var route = routeFromHash();
    showPage(route.page, route.anchor, false);
    on(window, "hashchange", function () {
      var next = routeFromHash();
      showPage(next.page, next.anchor, false);
    });
  } else {
    var active = doc.body.getAttribute("data-page");
    if (active) { markNav(active); }
  }

  /* -------------------------------------------------------- table of contents */

  var tocLinks = $$(".site-toc a[data-anchor]");
  if (tocLinks.length && "IntersectionObserver" in window) {
    var byId = {};
    tocLinks.forEach(function (link) { byId[link.getAttribute("data-anchor")] = link; });
    var seen = [];
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        var id = entry.target.id;
        var at = seen.indexOf(id);
        if (entry.isIntersecting) { if (at < 0) { seen.push(id); } }
        else if (at >= 0) { seen.splice(at, 1); }
      });
      var current = seen.length ? seen[0] : null;
      tocLinks.forEach(function (link) { link.removeAttribute("data-active"); });
      if (current && byId[current]) { byId[current].setAttribute("data-active", "yes"); }
    }, { rootMargin: "-72px 0px -70% 0px", threshold: 0 });
    $$(".doc-h").forEach(function (heading) { if (heading.id) { observer.observe(heading); } });
  }

  /* ------------------------------------------------------------------- copy */

  function fallbackCopy(text) {
    var area = doc.createElement("textarea");
    area.value = text;
    area.setAttribute("readonly", "readonly");
    area.style.position = "fixed";
    area.style.opacity = "0";
    doc.body.appendChild(area);
    area.select();
    var ok = false;
    try { ok = doc.execCommand("copy"); } catch (err) { ok = false; }
    doc.body.removeChild(area);
    return ok;
  }

  $$("button[data-copy]").forEach(function (button) {
    on(button, "click", function () {
      var block = button.closest(".doc-code");
      var code = block ? $("code", block) : null;
      if (!code) { return; }
      var text = code.textContent;
      var label = $(".doc-copy-label", button);
      var settle = function (ok) {
        button.setAttribute("data-state", ok ? "done" : "fail");
        if (label) { label.textContent = ok ? "Copied" : "Press Ctrl+C"; }
        window.setTimeout(function () {
          button.removeAttribute("data-state");
          if (label) { label.textContent = "Copy"; }
        }, 1600);
      };
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(function () { settle(true); },
                                                 function () { settle(fallbackCopy(text)); });
      } else {
        settle(fallbackCopy(text));
      }
    });
  });

  /* ----------------------------------------------------------------- search */

  var LOW = new Array(REC.length);
  var HEAD = new Array(REC.length);
  for (var i = 0; i < REC.length; i++) {
    LOW[i] = (REC[i].t || "").toLowerCase();
    HEAD[i] = (REC[i].h || "").toLowerCase();
  }

  var overlay = $("#search-overlay");
  var input = $("#search-input");
  var list = $("#search-results");
  var status = $("#search-status");
  var cursor = -1;
  var hits = [];

  function escapeHtml(text) {
    return String(text).replace(/[&<>"]/g, function (ch) {
      return ch === "&" ? "&amp;" : ch === "<" ? "&lt;" : ch === ">" ? "&gt;" : "&quot;";
    });
  }
  function escapeRe(text) { return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

  function hrefFor(record) {
    var page = PAGES[record.p];
    if (!page) { return "#"; }
    if (SINGLE) { return "#" + (record.a ? page.s + "__" + record.a : page.s); }
    return page.u + (record.a ? "#" + record.a : "");
  }

  function snippet(record, terms) {
    var text = record.t || "";
    var low = text.toLowerCase();
    var at = -1;
    for (var t = 0; t < terms.length && at < 0; t++) { at = low.indexOf(terms[t]); }
    if (at < 0) { at = 0; }
    var from = Math.max(0, at - 70);
    var slice = text.slice(from, from + 210);
    var out = escapeHtml((from > 0 ? "…" : "") + slice + (from + 210 < text.length ? "…" : ""));
    terms.forEach(function (term) {
      if (!term) { return; }
      out = out.replace(new RegExp("(" + escapeRe(escapeHtml(term)) + ")", "ig"), "<mark>$1</mark>");
    });
    return out;
  }

  function runSearch(query) {
    var terms = query.toLowerCase().split(/\s+/).filter(function (t) { return t.length > 0; });
    if (!terms.length) { return []; }
    var found = [];
    for (var r = 0; r < REC.length; r++) {
      var score = 0;
      var earliest = 1e9;
      var matched = true;
      for (var t = 0; t < terms.length; t++) {
        var term = terms[t];
        var inHead = HEAD[r].indexOf(term);
        var inBody = LOW[r].indexOf(term);
        if (inHead < 0 && inBody < 0) { matched = false; break; }
        if (inHead >= 0) { score += inHead === 0 ? 60 : 40; }
        if (inBody >= 0) {
          score += 8;
          if (inBody < earliest) { earliest = inBody; }
          if (new RegExp("\\b" + escapeRe(term)).test(LOW[r])) { score += 6; }
        }
      }
      if (!matched) { continue; }
      score += Math.max(0, 14 - (REC[r].l || 3) * 2);
      found.push({ rec: REC[r], score: score, at: earliest === 1e9 ? 0 : earliest, seq: r });
    }
    found.sort(function (a, b) { return (b.score - a.score) || (a.at - b.at) || (a.seq - b.seq); });
    return found.slice(0, 50);
  }

  function highlightCursor() {
    $$("li", list).forEach(function (li, index) {
      if (index === cursor) {
        li.setAttribute("data-active", "yes");
        var anchor = $("a", li);
        if (anchor && anchor.scrollIntoView) { anchor.scrollIntoView({ block: "nearest" }); }
        if (input) { input.setAttribute("aria-activedescendant", anchor ? anchor.id : ""); }
      } else {
        li.removeAttribute("data-active");
      }
    });
  }

  function render(query) {
    if (!list) { return; }
    hits = runSearch(query);
    cursor = hits.length ? 0 : -1;
    list.textContent = "";
    if (!query.trim()) {
      if (status) { status.textContent = "Type to search every page of this help set."; }
      return;
    }
    if (!hits.length) {
      if (status) { status.textContent = "No matches for “" + query + "”."; }
      return;
    }
    if (status) {
      status.textContent = hits.length + (hits.length === 1 ? " match" : " matches") +
        (hits.length === 50 ? " (showing the first 50)" : "");
    }
    var terms = query.toLowerCase().split(/\s+/).filter(function (t) { return t.length > 0; });
    var frag = doc.createDocumentFragment();
    hits.forEach(function (hit, index) {
      var record = hit.rec;
      var page = PAGES[record.p] || { t: "" };
      var li = doc.createElement("li");
      var a = doc.createElement("a");
      a.id = "search-hit-" + index;
      a.href = hrefFor(record);
      a.setAttribute("role", "option");
      var crumb = doc.createElement("span");
      crumb.className = "site-result-crumb";
      crumb.textContent = page.t;
      var title = doc.createElement("span");
      title.className = "site-result-title";
      title.textContent = record.h || page.t;
      var snip = doc.createElement("span");
      snip.className = "site-result-snip";
      snip.innerHTML = snippet(record, terms);
      a.appendChild(crumb);
      a.appendChild(title);
      a.appendChild(snip);
      on(a, "click", function (event) {
        if (SINGLE) {
          event.preventDefault();
          closeSearch();
          showPage(page.s, record.a, true);
        } else {
          closeSearch();
        }
      });
      li.appendChild(a);
      frag.appendChild(li);
    });
    list.appendChild(frag);
    highlightCursor();
  }

  function openSearch(seed) {
    if (!overlay) { return; }
    overlay.removeAttribute("hidden");
    doc.body.setAttribute("data-search", "open");
    if (input) {
      if (typeof seed === "string") { input.value = seed; }
      input.focus();
      input.select();
      render(input.value);
    }
  }

  function closeSearch() {
    if (!overlay) { return; }
    overlay.setAttribute("hidden", "hidden");
    doc.body.removeAttribute("data-search");
    var button = $("#search-open");
    if (button && typeof button.focus === "function") { button.focus(); }
  }

  on($("#search-open"), "click", function () { openSearch(""); });
  on(overlay, "click", function (event) { if (event.target === overlay) { closeSearch(); } });
  on($("#search-close"), "click", closeSearch);
  on(input, "input", function () { render(input.value); });

  on(input, "keydown", function (event) {
    if (!hits.length && event.key !== "Escape") { return; }
    if (event.key === "ArrowDown") {
      event.preventDefault();
      cursor = (cursor + 1) % hits.length;
      highlightCursor();
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      cursor = (cursor - 1 + hits.length) % hits.length;
      highlightCursor();
    } else if (event.key === "Home") {
      event.preventDefault(); cursor = 0; highlightCursor();
    } else if (event.key === "End") {
      event.preventDefault(); cursor = hits.length - 1; highlightCursor();
    } else if (event.key === "Enter") {
      event.preventDefault();
      var items = $$("li a", list);
      if (items[cursor]) { items[cursor].click(); }
    }
  });

  on(doc, "keydown", function (event) {
    var open = overlay && !overlay.hasAttribute("hidden");
    if (event.key === "Escape") {
      if (open) { event.preventDefault(); closeSearch(); }
      else if (doc.body.getAttribute("data-nav") === "open") { doc.body.setAttribute("data-nav", "closed"); }
      return;
    }
    if (open) { return; }
    var target = event.target || {};
    var tag = (target.tagName || "").toLowerCase();
    if (tag === "input" || tag === "textarea" || tag === "select" || target.isContentEditable) { return; }
    if (event.key === "/" && !event.ctrlKey && !event.metaKey && !event.altKey) {
      event.preventDefault();
      openSearch("");
    } else if ((event.key === "k" || event.key === "K") && (event.ctrlKey || event.metaKey)) {
      event.preventDefault();
      openSearch("");
    }
  });
})();
"""
