"""Stylesheet assembly for the help site.

The site does not invent colours. It embeds a verbatim copy of
``src/chaos/web/tokens.css`` at build time and codes against the same token
names the operator console uses, so the help reads as part of the same product
and tracks the console's palette automatically on the next build.

Two things are derived from that copy rather than hand-written:

* ``:root[data-theme="dark"]`` — the base ``:root`` declarations, re-emitted so
  an explicit "dark" choice beats a light operating system.
* ``:root[data-theme="light"]`` — the declarations inside tokens.css's
  ``@media (prefers-color-scheme: light)`` block, re-emitted so an explicit
  "light" choice beats a dark operating system.

If tokens.css is ever restructured so those blocks cannot be found, the
derivation is skipped and the site falls back to following the operating
system; the build says so rather than shipping a dead toggle.
"""

from __future__ import annotations

import re

_ROOT_BLOCK_RE = re.compile(r"(?m)^:root\s*\{")
_LIGHT_MEDIA_RE = re.compile(r"(?m)^@media\s*\(prefers-color-scheme:\s*light\)\s*\{")


def _balanced_block(css: str, open_brace: int) -> tuple[str, int] | None:
    depth = 0
    index = open_brace
    while index < len(css):
        char = css[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return css[open_brace + 1 : index], index + 1
        index += 1
    return None


def _strip_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)


def derive_theme_overrides(tokens_css: str) -> tuple[str, list[str]]:
    """Build explicit ``[data-theme]`` blocks from the token file."""
    warnings: list[str] = []
    blocks: list[str] = []

    root = _ROOT_BLOCK_RE.search(tokens_css)
    if root is None:
        warnings.append("tokens.css: no top-level :root block found; explicit dark theme not derived")
    else:
        found = _balanced_block(tokens_css, root.end() - 1)
        if found is None:
            warnings.append("tokens.css: unbalanced :root block; explicit dark theme not derived")
        else:
            body = _strip_comments(found[0]).strip()
            blocks.append(':root[data-theme="dark"] {\n' + body + "\n}")

    media = _LIGHT_MEDIA_RE.search(tokens_css)
    if media is None:
        warnings.append("tokens.css: no prefers-color-scheme:light block; explicit light theme not derived")
    else:
        found = _balanced_block(tokens_css, media.end() - 1)
        if found is None:
            warnings.append("tokens.css: unbalanced light media block; explicit light theme not derived")
        else:
            inner = found[0]
            inner_root = _ROOT_BLOCK_RE.search(inner) or re.search(r":root\s*\{", inner)
            if inner_root is None:
                warnings.append("tokens.css: light block has no :root; explicit light theme not derived")
            else:
                nested = _balanced_block(inner, inner_root.end() - 1)
                if nested is None:
                    warnings.append("tokens.css: unbalanced light :root; explicit light theme not derived")
                else:
                    body = _strip_comments(nested[0]).strip()
                    blocks.append(':root[data-theme="light"] {\n' + body + "\n}")

    if not blocks:
        return "", warnings
    header = (
        "/* ---------------------------------------------------------------------\n"
        "   Explicit theme selection, derived from tokens.css at build time.\n"
        "   The media query above still decides when no choice has been made.\n"
        "   --------------------------------------------------------------------- */\n"
    )
    return header + "\n\n".join(blocks) + "\n", warnings


SITE_CSS = """
/* ===========================================================================
   Project CHAOS — help site
   ---------------------------------------------------------------------------
   Same rules as the operator console it belongs to: system fonts only, no
   webfonts, no CDN, no build step, no absolute URL anywhere in the file. Every
   colour, radius, duration and shadow comes from the tokens above.

   The site is generated by tools/build_docs.py. Editing this file by hand is
   editing a build artefact; change tools/docsite/theme.py instead.
   =========================================================================== */

*, *::before, *::after { box-sizing: border-box; }

html { font-size: var(--fs-base); scroll-behavior: smooth; scroll-padding-top: 4.6rem; }
@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  * { animation-duration: 1ms !important; transition-duration: 1ms !important; }
}

body {
  margin: 0;
  background: var(--surface-0);
  color: var(--text-1);
  font-family: var(--font-sans);
  font-size: 1rem;
  line-height: 1.55;
  -webkit-text-size-adjust: 100%;
  -webkit-font-smoothing: antialiased;
}

a { color: var(--accent); text-decoration-color: color-mix(in srgb, var(--accent) 45%, transparent); }
a:hover { text-decoration-thickness: 2px; }

code, pre, kbd, samp { font-family: var(--font-mono); }

::selection { background: var(--accent-soft); color: var(--text-1); }

* { scrollbar-color: var(--stroke-strong) transparent; scrollbar-width: thin; }
::-webkit-scrollbar { width: 10px; height: 10px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb {
  background: var(--stroke-strong); border: 2px solid transparent;
  border-radius: var(--radius-pill); background-clip: padding-box;
}

:focus-visible {
  outline: var(--focus-ring-width) solid var(--focus);
  outline-offset: var(--focus-ring-offset);
  border-radius: var(--radius-xs);
  box-shadow: var(--focus-halo);
}

.visually-hidden {
  position: absolute; width: 1px; height: 1px; margin: -1px;
  padding: 0; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; border: 0;
}

.skip-link {
  position: absolute; left: -9999px; top: 0; z-index: 100;
  background: var(--accent); color: var(--accent-ink);
  padding: .6rem 1rem; border-radius: 0 0 var(--radius-sm) 0; font-weight: 600;
}
.skip-link:focus { left: 0; }

.icon { width: 1.15em; height: 1.15em; fill: none; stroke: currentColor;
        stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round; flex: none; }

/* ------------------------------------------------------------------ topbar */

.site-topbar {
  display: flex; align-items: center; gap: var(--gap);
  padding: .55rem 1rem;
  background: var(--surface-1);
  border-bottom: 1px solid var(--stroke-1);
  box-shadow: var(--shadow-1);
  position: sticky; top: 0; z-index: 30;
}

.site-identity { display: flex; align-items: center; gap: .7rem; min-width: 0; text-decoration: none; color: inherit; }
.site-mark {
  width: 2.1rem; height: 2.1rem; display: grid; place-items: center;
  background: var(--surface-sunken); border: 1px solid var(--stroke-1); border-radius: var(--radius-sm);
}
.site-mark svg { width: 1.5rem; height: 1.5rem; fill: none; stroke: var(--accent); stroke-width: 2.2; stroke-linejoin: round; }
.site-titles h1 { margin: 0; font-size: 1rem; font-weight: 650; letter-spacing: -.01em; white-space: nowrap; }
.site-titles p { margin: 0; font-size: .76rem; color: var(--text-2); white-space: nowrap; }

.site-tools { margin-left: auto; display: flex; align-items: center; gap: .45rem; }

.btn {
  display: inline-flex; align-items: center; gap: .4rem;
  font: inherit; font-size: .85rem; font-weight: 550;
  padding: .4rem .7rem;
  color: var(--text-1); background: var(--surface-input);
  border: 1px solid var(--stroke-strong); border-radius: var(--radius-sm);
  cursor: pointer;
  transition: background var(--dur-fast) var(--ease), border-color var(--dur-fast) var(--ease);
}
.btn:hover { background: var(--surface-2); border-color: var(--accent); }
.btn:active { background: var(--surface-3); transform: translateY(1px); }
.btn-icon { padding: .4rem; }
.btn-sm { font-size: .78rem; padding: .25rem .55rem; }

/* The search launcher looks like the field it opens. */
.site-searchbtn {
  display: flex; align-items: center; gap: .5rem;
  min-width: 15rem; max-width: 24rem; flex: 1 1 18rem;
  padding: .38rem .6rem;
  font: inherit; font-size: .85rem; text-align: left;
  color: var(--text-2); background: var(--surface-input);
  border: 1px solid var(--stroke-strong); border-radius: var(--radius-sm);
  cursor: pointer;
}
.site-searchbtn:hover { border-color: var(--accent); color: var(--text-1); }
.site-searchbtn .kbd-hint { margin-left: auto; }

kbd, .kbd-hint {
  font-family: var(--font-mono); font-size: .72rem; line-height: 1.4;
  padding: .05rem .35rem;
  color: var(--text-2); background: var(--surface-sunken);
  border: 1px solid var(--stroke-strong); border-bottom-width: 2px;
  border-radius: var(--radius-xs);
}

/* ------------------------------------------------------------------- shell */

.site-shell {
  display: grid;
  grid-template-columns: 16rem minmax(0, 1fr) 15rem;
  align-items: start;
  gap: 0;
  max-width: 100rem; margin: 0 auto;
}

.site-nav {
  position: sticky; top: var(--chrome-topbar-h);
  max-height: calc(100vh - var(--chrome-topbar-h));
  overflow-y: auto;
  padding: var(--gap) .55rem var(--space-7);
  border-right: 1px solid var(--stroke-1);
}
.site-nav h2 {
  margin: var(--space-5) .7rem .3rem;
  font-size: .7rem; font-weight: 700; text-transform: uppercase; letter-spacing: .09em;
  color: var(--text-3);
}
.site-nav h2:first-child { margin-top: 0; }
.site-nav ul { list-style: none; margin: 0; padding: 0; }
.site-nav a {
  display: flex; align-items: center; gap: .5rem;
  padding: .38rem .7rem; border-radius: var(--radius-sm);
  text-decoration: none; color: var(--text-2);
  font-size: .88rem; font-weight: 500; line-height: 1.35;
  transition: background var(--dur-fast) var(--ease), color var(--dur-fast) var(--ease);
}
.site-nav a:hover { background: var(--surface-2); color: var(--text-1); }
.site-nav a[aria-current="page"] {
  background: var(--surface-2); color: var(--text-1); font-weight: 650;
  box-shadow: inset 3px 0 0 var(--accent);
}
.site-nav .nav-num {
  min-width: 1.4rem; font-family: var(--font-mono); font-size: .72rem;
  color: var(--text-3); font-variant-numeric: tabular-nums;
}

.site-main { padding: var(--space-6) var(--space-7) var(--space-7); min-width: 0; }
.site-main:focus { outline: none; }

/* --------------------------------------------------------------------- toc */

.site-toc {
  position: sticky; top: var(--chrome-topbar-h);
  max-height: calc(100vh - var(--chrome-topbar-h));
  overflow-y: auto;
  padding: var(--gap) var(--space-4) var(--space-7);
  font-size: .82rem;
}
.site-toc h2 {
  margin: 0 0 .4rem; font-size: .7rem; font-weight: 700;
  text-transform: uppercase; letter-spacing: .09em; color: var(--text-3);
}
.site-toc ul { list-style: none; margin: 0; padding: 0; border-left: 1px solid var(--stroke-1); }
.site-toc a {
  display: block; padding: .22rem .6rem; color: var(--text-2);
  text-decoration: none; border-left: 2px solid transparent; margin-left: -1px;
  overflow-wrap: anywhere;
}
.site-toc a:hover { color: var(--text-1); }
.site-toc a[data-active="yes"] { color: var(--accent); border-left-color: var(--accent); font-weight: 600; }
.site-toc li[data-level="3"] a { padding-left: 1.3rem; }
.site-toc li[data-level="4"] a { padding-left: 2rem; font-size: .78rem; }
.site-toc li[data-level="5"] a,
.site-toc li[data-level="6"] a { padding-left: 2.6rem; font-size: .76rem; }

/* ----------------------------------------------------------------- article */

.doc-page { max-width: 62rem; }
.doc-page[hidden] { display: none; }

.doc-breadcrumb {
  display: flex; flex-wrap: wrap; gap: .35rem;
  margin: 0 0 .5rem; font-size: .76rem; color: var(--text-3);
}
.doc-breadcrumb span::after { content: "/"; margin-left: .35rem; color: var(--stroke-strong); }
.doc-breadcrumb span:last-child::after { content: ""; }

.doc-source {
  display: inline-flex; align-items: center; gap: .4rem;
  margin: 0 0 var(--space-5); padding: .18rem .5rem;
  font-family: var(--font-mono); font-size: .72rem; color: var(--text-3);
  background: var(--surface-sunken); border: 1px solid var(--stroke-1); border-radius: var(--radius-pill);
}

.doc-body { min-width: 0; }
.doc-body > :first-child { margin-top: 0; }

.doc-h { position: relative; scroll-margin-top: 4.6rem; font-weight: 650; letter-spacing: -.01em; line-height: 1.25; }
h1.doc-h { font-size: 1.85rem; margin: 0 0 var(--space-5); }
h2.doc-h {
  font-size: 1.32rem; margin: var(--space-7) 0 var(--space-4);
  padding-bottom: .3rem; border-bottom: 1px solid var(--stroke-1);
}
h3.doc-h { font-size: 1.08rem; margin: var(--space-6) 0 var(--space-3); }
h4.doc-h { font-size: .96rem; margin: var(--space-5) 0 var(--space-3); color: var(--text-1); }
h5.doc-h, h6.doc-h { font-size: .88rem; margin: var(--space-5) 0 var(--space-2); color: var(--text-2); }

.doc-anchor {
  margin-left: .4rem; padding: 0 .2rem;
  color: var(--text-3); text-decoration: none; font-weight: 500;
  opacity: 0; transition: opacity var(--dur-fast) var(--ease);
}
.doc-anchor::before { content: "#"; }
.doc-h:hover .doc-anchor, .doc-anchor:focus-visible { opacity: 1; }
.doc-anchor:hover { color: var(--accent); }

.doc-body p { margin: 0 0 var(--space-4); }
.doc-body ul, .doc-body ol { margin: 0 0 var(--space-4); padding-left: 1.5rem; }
.doc-body li { margin: .2rem 0; }
.doc-body li > ul, .doc-body li > ol { margin: .2rem 0; }
.doc-body ul { list-style: disc; }
.doc-body ul ul { list-style: circle; }
.doc-body ol { list-style: decimal; }
.doc-body li::marker { color: var(--text-3); }

.doc-body hr { border: 0; border-top: 1px solid var(--stroke-2); margin: var(--space-7) 0; }

.doc-body :not(pre) > code {
  font-size: .875em;
  padding: .1em .35em;
  color: var(--accent-strong);
  background: var(--surface-sunken);
  border: 1px solid var(--stroke-1);
  border-radius: var(--radius-xs);
  overflow-wrap: anywhere;
}
:root[data-theme="light"] .doc-body :not(pre) > code,
.doc-body :not(pre) > code { color: var(--accent); }

.doc-body blockquote {
  margin: 0 0 var(--space-4); padding: .1rem var(--space-5);
  border-left: 3px solid var(--stroke-strong);
  color: var(--text-2); background: var(--surface-1);
  border-radius: 0 var(--radius-sm) var(--radius-sm) 0;
}
.doc-body blockquote > :last-child { margin-bottom: 0; }

.doc-alert {
  margin: 0 0 var(--space-4); padding: var(--space-4) var(--space-5);
  border: 1px solid var(--stroke-1); border-left-width: 4px;
  border-radius: var(--radius-sm);
  background: var(--surface-1);
}
.doc-alert > :last-child { margin-bottom: 0; }
.doc-alert-head {
  margin: 0 0 .3rem !important;
  font-size: .74rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em;
}
.doc-alert[data-tone="info"]     { border-left-color: var(--sev-info);     background: var(--sev-info-soft); }
.doc-alert[data-tone="info"] .doc-alert-head { color: var(--sev-info); }
.doc-alert[data-tone="ok"]       { border-left-color: var(--status-ok);    background: var(--status-ok-soft); }
.doc-alert[data-tone="ok"] .doc-alert-head { color: var(--status-ok); }
.doc-alert[data-tone="major"]    { border-left-color: var(--sev-major);    background: var(--sev-major-soft); }
.doc-alert[data-tone="major"] .doc-alert-head { color: var(--sev-major); }
.doc-alert[data-tone="warning"]  { border-left-color: var(--sev-warning);  background: var(--sev-warning-soft); }
.doc-alert[data-tone="warning"] .doc-alert-head { color: var(--sev-warning); }
.doc-alert[data-tone="critical"] { border-left-color: var(--sev-critical); background: var(--sev-critical-soft); }
.doc-alert[data-tone="critical"] .doc-alert-head { color: var(--sev-critical); }

/* ------------------------------------------------------------------ tables */

.doc-table-wrap {
  overflow-x: auto; margin: 0 0 var(--space-5);
  border: 1px solid var(--stroke-1); border-radius: var(--radius);
  background: var(--surface-1);
}
.doc-table-wrap table { width: 100%; border-collapse: collapse; font-size: .85rem; }
.doc-table-wrap th, .doc-table-wrap td {
  text-align: left; padding: .45rem .7rem;
  border-bottom: 1px solid var(--stroke-1); vertical-align: top;
}
.doc-table-wrap th {
  color: var(--text-2); font-weight: 600; font-size: .74rem;
  text-transform: uppercase; letter-spacing: .05em;
  background: var(--surface-1); box-shadow: inset 0 -1px 0 var(--stroke-2);
  white-space: nowrap;
}
.doc-table-wrap tbody tr:last-child td { border-bottom: none; }
.doc-table-wrap tbody tr:hover { background: var(--surface-2); }
.doc-table-wrap .col-right  { text-align: right; font-variant-numeric: tabular-nums; }
.doc-table-wrap .col-center { text-align: center; }

/* -------------------------------------------------------------------- code */

.doc-code {
  margin: 0 0 var(--space-5);
  border: 1px solid var(--stroke-1); border-radius: var(--radius);
  background: var(--surface-sunken); overflow: hidden;
}
.doc-code-bar {
  display: flex; align-items: center; gap: .5rem;
  padding: .25rem .35rem .25rem .7rem;
  background: var(--surface-1); border-bottom: 1px solid var(--stroke-1);
}
.doc-code-lang {
  font-family: var(--font-mono); font-size: .68rem; letter-spacing: .08em;
  text-transform: uppercase; color: var(--text-3);
}
.doc-copy {
  margin-left: auto;
  font: inherit; font-size: .72rem; font-family: var(--font-sans);
  padding: .15rem .5rem; cursor: pointer;
  color: var(--text-2); background: transparent;
  border: 1px solid var(--stroke-1); border-radius: var(--radius-xs);
  transition: color var(--dur-fast) var(--ease), border-color var(--dur-fast) var(--ease);
}
.doc-copy:hover { color: var(--text-1); border-color: var(--accent); }
.doc-copy[data-state="done"] { color: var(--status-ok); border-color: var(--status-ok); }

.doc-pre {
  margin: 0; padding: var(--space-4) var(--space-5);
  overflow-x: auto; font-size: .82rem; line-height: 1.55;
  color: var(--text-1); tab-size: 4;
}
.doc-pre code { background: none; border: 0; padding: 0; color: inherit; font-size: inherit; }

.t-c { color: var(--text-3); font-style: italic; }
.t-s { color: var(--status-ok); }
.t-n { color: var(--sev-warning); }
.t-k { color: var(--sev-emergency); font-weight: 600; }
.t-t { color: var(--sev-info); }
.t-p { color: var(--status-no-data); }
.t-v { color: var(--status-design-only); }
.t-f { color: var(--sev-info); font-weight: 600; }
.t-o { color: var(--text-2); }
.t-a { color: var(--status-ok); }
.t-d { color: var(--sev-critical); }

.doc-diagram {
  margin: 0 0 var(--space-5); padding: 0;
  border: 1px dashed var(--stroke-strong); border-radius: var(--radius);
  background: var(--surface-sunken); overflow: hidden;
}
.doc-diagram figcaption {
  display: flex; align-items: center; gap: .5rem; flex-wrap: wrap;
  padding: .4rem .7rem; font-size: .74rem; color: var(--text-3);
  background: var(--surface-1); border-bottom: 1px dashed var(--stroke-strong);
}
.doc-diagram-tag {
  font-size: .66rem; font-weight: 700; letter-spacing: .09em; text-transform: uppercase;
  color: var(--cat-label); background: var(--cat-structure);
  padding: .05rem .4rem; border-radius: var(--radius-xs);
}

/* ------------------------------------------------------------- other marks */

.doc-figure { margin: 0 0 var(--space-5); }
.doc-figure img { max-width: 100%; height: auto; border-radius: var(--radius-sm); }
.doc-figure figcaption { margin-top: .4rem; font-size: .78rem; color: var(--text-3); }

.repo-ref {
  font-family: var(--font-mono); font-size: .875em;
  padding: .1em .35em;
  color: var(--text-2); background: var(--surface-sunken);
  border: 1px dashed var(--stroke-strong); border-radius: var(--radius-xs);
  overflow-wrap: anywhere;
}
/* Beats `.doc-body :not(pre) > code` on specificity: a code span inside the
   chip must not draw a second box. */
.doc-body .repo-ref > code {
  padding: 0; border: 0; background: none; color: inherit; font-size: inherit;
}

.x-link::after {
  content: "\\2197"; font-size: .75em; margin-left: .15em;
  color: var(--text-3); vertical-align: super;
}

.doc-tasklist { list-style: none !important; padding-left: .2rem !important; }
.doc-task { display: flex; gap: .55rem; align-items: flex-start; }
.doc-task input { margin-top: .35rem; accent-color: var(--accent); flex: none; }
.doc-task[data-state="done"] > span { color: var(--text-3); }

.doc-footnotes { margin-top: var(--space-7); padding-top: var(--space-4); border-top: 1px solid var(--stroke-2); }
.doc-footnotes h2 { font-size: .8rem; text-transform: uppercase; letter-spacing: .08em; color: var(--text-3); }
.doc-footnotes ol { font-size: .88rem; color: var(--text-2); }
.fn-ref a { text-decoration: none; }
.fn-back { margin-left: .4rem; text-decoration: none; }

.doc-warning {
  margin: 0 0 var(--space-5); padding: var(--space-3) var(--space-4);
  border: 1px dashed var(--sev-warning); border-radius: var(--radius-sm);
  background: var(--sev-warning-soft); font-size: .82rem; color: var(--text-2);
}

/* ---------------------------------------------------------------- prev/next */

.doc-pager {
  display: grid; grid-template-columns: 1fr 1fr; gap: var(--gap);
  margin-top: var(--space-7); padding-top: var(--space-5);
  border-top: 1px solid var(--stroke-2);
}
.doc-pager a {
  display: block; padding: .6rem .8rem;
  border: 1px solid var(--stroke-1); border-radius: var(--radius);
  background: var(--surface-1); text-decoration: none; color: var(--text-1);
  transition: border-color var(--dur-fast) var(--ease);
}
.doc-pager a:hover { border-color: var(--accent); }
.doc-pager .pager-role { display: block; font-size: .7rem; text-transform: uppercase; letter-spacing: .08em; color: var(--text-3); }
.doc-pager .pager-next { text-align: right; grid-column: 2; }

/* ------------------------------------------------------------------ search */

.site-search[hidden] { display: none; }
.site-search {
  position: fixed; inset: 0; z-index: 60;
  background: var(--surface-scrim);
  display: flex; justify-content: center; align-items: flex-start;
  padding: 4rem 1rem 1rem;
}
.site-search-panel {
  width: min(46rem, 100%); max-height: min(34rem, 80vh);
  display: flex; flex-direction: column;
  background: var(--surface-1); border: 1px solid var(--stroke-2);
  border-radius: var(--radius-lg); box-shadow: var(--shadow-3); overflow: hidden;
}
.site-search-head { display: flex; align-items: center; gap: .5rem; padding: .6rem .7rem; border-bottom: 1px solid var(--stroke-1); }
.site-search-head input {
  flex: 1 1 auto; font: inherit; font-size: 1rem;
  color: var(--text-1); background: var(--surface-input);
  border: 1px solid var(--stroke-strong); border-radius: var(--radius-sm);
  padding: .45rem .6rem;
}
.site-search-status { padding: .35rem .8rem; font-size: .74rem; color: var(--text-3); border-bottom: 1px solid var(--stroke-1); }
.site-results { list-style: none; margin: 0; padding: .3rem; overflow-y: auto; }
.site-results li { margin: 0; }
.site-results a {
  display: block; padding: .5rem .6rem; border-radius: var(--radius-sm);
  text-decoration: none; color: var(--text-1);
}
.site-results a:hover, .site-results li[data-active="yes"] a { background: var(--surface-2); }
.site-results li[data-active="yes"] a { box-shadow: inset 3px 0 0 var(--accent); }
.site-result-crumb { display: block; font-size: .7rem; color: var(--text-3); text-transform: uppercase; letter-spacing: .06em; }
.site-result-title { display: block; font-weight: 600; font-size: .92rem; }
.site-result-snip { display: block; font-size: .8rem; color: var(--text-2); margin-top: .15rem; }
.site-results mark { background: var(--accent-soft); color: var(--accent-strong); border-radius: var(--radius-xs); padding: 0 .1em; }
:root[data-theme="light"] .site-results mark { color: var(--accent); }
.site-search-foot {
  display: flex; gap: .8rem; flex-wrap: wrap;
  padding: .4rem .8rem; font-size: .72rem; color: var(--text-3);
  border-top: 1px solid var(--stroke-1); background: var(--surface-sunken);
}

/* ------------------------------------------------------------------ mobile */

.site-navtoggle { display: none; }

@media (max-width: 1180px) {
  .site-shell { grid-template-columns: 15rem minmax(0, 1fr); }
  .site-toc { display: none; }
}
@media (max-width: 860px) {
  .site-shell { grid-template-columns: minmax(0, 1fr); }
  .site-navtoggle { display: inline-flex; }
  .site-nav {
    position: fixed; inset: var(--chrome-topbar-h) auto 0 0; width: 17rem; z-index: 25;
    background: var(--surface-1); border-right: 1px solid var(--stroke-2);
    box-shadow: var(--shadow-3);
    transform: translateX(-100%); transition: transform var(--dur) var(--ease);
    max-height: none;
  }
  body[data-nav="open"] .site-nav { transform: none; }
  .site-main { padding: var(--space-5) var(--space-4) var(--space-7); }

  /* The topbar has four things and not enough room. Nothing is allowed to
     overlap: the identity and the search field give up width, in that order,
     and the controls keep theirs because they are the only way out of a
     narrow screen. */
  .site-topbar { gap: .5rem; padding: .5rem .6rem; }
  .site-identity { min-width: 0; flex: 0 1 auto; overflow: hidden; }
  .site-titles { min-width: 0; }
  .site-titles h1 { overflow: hidden; text-overflow: ellipsis; }
  .site-titles p { display: none; }
  .site-searchbtn { min-width: 0; flex: 1 1 4rem; }
  .site-searchbtn .kbd-hint { display: none; }
  .site-searchbtn span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .site-tools { flex: 0 0 auto; }
}

@media (max-width: 560px) {
  .site-titles { display: none; }
  .site-searchbtn span:not(.kbd-hint) { display: none; }
  .site-searchbtn { flex: 0 0 auto; padding: .4rem; }
  .theme-label { display: none; }
  .btn { padding: .4rem; }
}

/* ------------------------------------------------------------------- print */

@media print {
  /* Re-point the tokens rather than patching component rules. Everything on
     the page already draws from these names, so one block turns the whole
     help set into ink on paper — including anything added later. Listing the
     [data-theme] selectors keeps this at the same specificity as the explicit
     theme blocks; being last in the file is what makes it win. */
  :root, :root[data-theme="dark"], :root[data-theme="light"] {
    --surface-0: #ffffff;
    --surface-1: #ffffff;
    --surface-2: #f3f3f3;
    --surface-3: #ebebeb;
    --surface-sunken: #f7f7f7;
    --surface-input: #ffffff;
    --surface-scrim: transparent;

    --stroke-1: #cccccc;
    --stroke-2: #aaaaaa;
    --stroke-strong: #888888;

    --text-1: #000000;
    --text-2: #2b2b2b;
    --text-3: #555555;
    --accent: #14532d;
    --accent-strong: #14532d;
    --accent-soft: transparent;
    --accent-ink: #ffffff;

    --shadow-1: none;
    --shadow-2: none;
    --shadow-3: none;
  }

  .site-topbar, .site-nav, .site-toc, .site-search, .doc-pager,
  .doc-copy, .doc-anchor, .doc-code-bar, .site-navtoggle { display: none !important; }

  html, body { background: #fff; color: #000; font-size: 10.5pt; }
  .site-shell { display: block; max-width: none; }
  .site-main { padding: 0; }
  .doc-page { max-width: none; }
  .doc-page[hidden] { display: none; }

  a { color: #000; text-decoration: underline; }
  .x-link::after { content: ""; }
  .doc-breadcrumb, .doc-source { color: #555; }

  /* Syntax colour is the one thing that does not survive monochrome: three
     token classes can print as the same grey. Structure carries it instead. */
  .doc-pre { white-space: pre-wrap; word-break: break-word; }
  .doc-pre [class^="t-"] { color: #000 !important; font-style: normal; }
  .doc-pre .t-c { color: #555 !important; font-style: italic; }
  .doc-pre .t-k { font-weight: 700; }

  .doc-code, .doc-table-wrap, .doc-diagram, .doc-alert, blockquote,
  .doc-figure, .doc-footnotes { break-inside: avoid; }
  .doc-h { break-after: avoid; }
  h1.doc-h { break-before: page; }
  .doc-page:first-of-type h1.doc-h { break-before: auto; }
  .doc-table-wrap { overflow-x: visible; }
  .doc-table-wrap table { font-size: 9pt; }
  .doc-table-wrap th { background: #f3f3f3; }
  .doc-alert { border: 1px solid #888; border-left-width: 4px; }
}
"""
